// SPDX-License-Identifier: GPL-3.0

pragma solidity >=0.4.17;

contract Inbox{
    string public message;

    function Inbox (string initialMessage) public {
        message = initialMessage;
    }

    function setMessage (string newMessage) public {
        message = newMessage;
    }

    // Already generated by the above message variable 
    // function getMessage () public view returns (string memory) {
    //     return message;
    // }
}